---
#
# Create AWS Security Group for Ping and SSH
#

  - name: Create SG-Ping+SSH Security Group
    amazon.aws.ec2_group:
      name: SG-Ping+SSH
      description: Allow Ping and SSH to Linux VM
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      rules:
        - proto: icmp
          from_port: -1
          to_port:  -1
          cidr_ip: "{{ aws_public_access_cidr}}"    # any
          rule_desc: Allow ICMP Ping
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ aws_public_access_cidr}}"    # any
          rule_desc: Allow SSH
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0    # any
      tags:
        Name: SG-Ping+SSH
        project: "{{ project_name }}"
        start_date: "{{ ansible_date_time.date }}"
    register: sg_ping_ssh

  - name: Show sg_ping_ssh
    ansible.builtin.debug: var=sg_ping_ssh


...