---
#------------------------------------------------------------------------------
# Create Node Instance in AWS EC2 
#------------------------------------------------------------------------------


  - name: Create Nodes
    community.aws.ec2_instance:
      state: started        # 💡 wait for started to get public IP address!
      name: "{{ item.name }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: "{{ subnet_private.subnet.id }}"
      image_id: "{{ item.image_id }}"
      instance_type: "{{ item.instance_type }}"
      key_name: "{{ item.ssh_keypair_name }}"
      security_group: "{{ sg_ping_ssh.group_name }}"
      network:
        assign_public_ip: yes
        delete_on_termination: yes
        private_ip_address: "{{ item.private_ip }}"
      volumes:
        - device_name: /dev/xvda
          ebs:
            delete_on_termination: true
            volume_size: "{{ item.volume_size }}"
      # wait: yes
      # wait_timeout: 300     # default: 600 seconds
      tags:
        Name: "{{ item.name }}"
        project: "{{ project_name }}"
        start_date: "{{ ansible_date_time.date }}"
    register: ec2

  - name: Show ec2
    ansible.builtin.debug: var=ec2


...
